// Generated by CoffeeScript 1.6.2
(function() {
  var repositionPopoup;

  repositionPopoup = function() {
    return $(".popout").each(function() {
      var bodyRight, bodyTop, popoutHeight, popoutLeft, popoutTop, popoutWidth;

      bodyRight = $("body").width();
      bodyTop = $("body").height();
      popoutLeft = $(this).offset().left;
      popoutTop = $(this).offset().top;
      popoutWidth = $(this).width();
      popoutHeight = $(this).height();
      if (bodyRight < (popoutLeft + popoutWidth)) {
        $(this).addClass("po-left");
        $(this).removeClass("po-right");
      } else {
        $(this).addClass("po-right");
        $(this).removeClass("po-left");
      }
      if (bodyTop < (popoutTop + popoutHeight)) {
        $(this).addClass("po-top");
        return $(this).removeClass("po-bottom");
      } else {
        $(this).addClass("po-bottom");
        return $(this).removeClass("po-top");
      }
    });
  };

  $(document).on('ready page:load', function() {
    return repositionPopoup();
  });

  $(window).on("resize", function() {
    return repositionPopoup();
  });

}).call(this);
